export const propertylist = [
    {
        id: 1,
        title: "Casagrand Florella",
        imgUrl: "https://www.casagrand.co.in/wp-content/uploads/2021/10/phase-2-banner-thumb-1.jpg?ver=1.200",
        address: "Sarjapura, Bangalore",
        location: "Bangalore",
        price: 11000,
        beds: 3,
        bathrooms: 4,
        area: 3300,
        date: new Date(),
        proptype: "Villa",
        popular: true,
        wishlisted: false,
    },
    {
        id: 2,
        title: "Casagrand Florella Phase 2",
        imgUrl: "https://www.casagrand.co.in/wp-content/uploads/2021/03/thumb-1.jpg?ver=1.200",
        address: "Sarjapura, Bangalore",
        location: "Bangalore",
        price: 12500,
        beds: 4,
        bathrooms: 4,
        area: 4500,
        date: new Date(),
        proptype: "Villa",
        popular: false,
        wishlisted: false,
    },
    {
        id: 3,
        title: "VK Gardends Propbuysell",
        imgUrl: "https://is1-3.housingcdn.com/4f2250e8/740405dce6903b7c7a52ab40c1804027/v0/medium/vk_gardens_propbuynsell-gandi_maisamma-hyderabad-vk_corporation.jpeg.webp",
        address: "Gandi Maisamma, North Hyderabad,",
        location: "Hyderabad",
        price: 4500,
        beds: 3,
        bathrooms: 3,
        area: 4000,
        date: new Date(),
        proptype: "Villa",
        popular: true,
        wishlisted: false,
    },
    {
        id: 4,
        title: "North Star",
        imgUrl: "https://www.nobroker.in/blog/wp-content/uploads/2022/07/10-Villa-Projects-In-Hyderabad-1.jpg",
        address: "Tellapur, Hyderabad",
        location: "Hyderabad",
        price: 9500,
        beds: 4,
        bathrooms: 3,
        area: 4200,
        date: new Date(),
        proptype: "Villa",
        popular: false,
        wishlisted: false,
    },
    {
        id: 5,
        title: "RK Villas",
        imgUrl: "https://media.istockphoto.com/photos/beautiful-luxury-villa-picture-id1221865614?k=20&m=1221865614&s=612x612&w=0&h=1bn78DlerF0eZTU7YkQh_4-n578FLWPV59FrMrpKxmc=",
        address: "Lonavala, Mumbai",
        location: "Mumbai",
        price: 8000,
        beds: 3,
        bathrooms: 4,
        area: 3800,
        date: new Date(),
        proptype: "Villa",
        popular: true,
        wishlisted: false,
    },
    {
        id: 6,
        title: "Asset Villas",
        imgUrl: "https://res.cloudinary.com/thrillophilia/image/upload/c_fill,dpr_2.0,f_auto,fl_progressive.strip_profile,g_center,h_230,q_auto,w_305/v1/filestore/ei26pavaw50cc05qxz1b4yi8q6kx_JPEG43.JPG",
        address: "Alibag, Mumbai",
        location: "Mumbai",
        price: 7000,
        beds: 2,
        bathrooms: 3,
        area: 3000,
        date: new Date(),
        proptype: "Villa",
        popular: false,
        wishlisted: false,
    },    {
        id: 7,
        title: "Deep Villa",
        imgUrl: "https://amazingarchitecture.com/storage/711/Deep-Villa-Atrey-and-Associates-New-Delhi-ndia-Amazing-Architecture-House.jpg",
        address: " Pitampura, New Delhi",
        location: "Delhi",
        price: 10500,
        beds: 4,
        bathrooms: 4,
        area: 3000,
        date: new Date(),
        proptype: "Villa",
        popular: true,
        wishlisted: false,
    },
    {
        id: 8,
        title: "Kautilya Marg",
        imgUrl: "https://img.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fsir.azureedge.net%2F1103i215%2Fgg8zvp9shpqwmst2fzn2yn6y04i215&option=N&h=472&permitphotoenlargement=false",
        address: "DL 110021, New Delhi",
        location: "Delhi",
        price: 12000,
        beds: 3,
        bathrooms: 3,
        area: 3000,
        date: new Date(),
        proptype: "Villa",
        popular: false,
        wishlisted: false,
    },
    {
        id: 9,
        title: "Casagrand Hazen",
        imgUrl: "https://www.casagrand.co.in/wp-content/uploads/2022/08/372-x-202.png?ver=1.200",
        address: "Bannerghatta Road, Bangalore",
        location: "Bangalore",
        price: 13000,
        beds: 3,
        bathrooms: 2,
        area: 1500,
        date: new Date(),
        proptype: "Apartment",
        popular: true,
        wishlisted: false,
    },
    {
        id: 10,
        title: "Casagrand Lorenza",
        imgUrl: "https://www.casagrand.co.in/wp-content/uploads/2018/12/1sideview.jpg?ver=1.200",
        address: "Hennur Main Road, Bangalore",
        location: "Bangalore",
        price: 12500,
        beds: 3,
        bathrooms: 3,
        area: 1800,
        date: new Date(),
        proptype: "Apartment",
        popular: true,
        wishlisted: false,
    },
    {
        id: 11,
        title: "Brigade Apartments",
        imgUrl: "https://cdn.brigadegroup.com/properties/gallery/1432013636555acb44e3462.jpg",
        address: "Banjara Hills, Hyderabad",
        location: "Hyderabad",
        price: 11000,
        beds: 2,
        bathrooms: 2,
        area: 1500,
        date: new Date(),
        proptype: "Apartment",
        popular: false,
        wishlisted: false,
    },
    {
        id: 12,
        title: "Prestige High Fields",
        imgUrl: "https://www.commercialproperty.review/wp-content/uploads/2021/03/Aparna-Serene-Park-Apartments-Kondapur-Hyderabad.jpg",
        address: "Kondapur, Hyderabad",
        location: "Hyderabad",
        price: 12000,
        beds: 3,
        bathrooms: 2,
        area: 1300,
        date: new Date(),
        proptype: "Apartment",
        popular: true,
        wishlisted: false,
    },
    {
        id: 13,
        title: "Starlite Lotus Apartments",
        imgUrl: "https://assets.architecturaldigest.in/photos/60083f49d0435267a8df9192/16:9/w_2560%2Cc_limit/mumbai-apartment-pka-interior-design-feature-02-866x487-1366x768.jpg",
        address: "Apartment Goregaon East, Mumbai",
        location: "Mumbai",
        price: 12300,
        beds: 3,
        bathrooms: 3,
        area: 1000,
        date: new Date(),
        proptype: "Apartment",
        popular: true,
        wishlisted: false,
    },
    {
        id: 14,
        title: "Karmvir Empire",
        imgUrl: "https://is1-3.housingcdn.com/4f2250e8/1712c407dcaabdd8bb6b45ee75072f9d/v6/fs/shree_developers_shree_siddhi_apartment_mumbai-seawoods-mumbai-shree_developers.jpg",
        address: "Apartment Chintal, Mumbai",
        location: "Mumbai",
        price: 9500,
        beds: 2,
        bathrooms: 3,
        area: 1020,
        date: new Date(),
        proptype: "Apartment",
        popular: false,
        wishlisted: false,
    },
    {
        id: 15,
        title: "Eros Hotel",
        imgUrl: "https://static.toiimg.com/photo/58015405.cms",
        address: "Nehru Place, Delhi",
        location: "Delhi",
        price: 14000,
        beds: 3,
        bathrooms: 4,
        area: 1700,
        date: new Date(),
        proptype: "Hotel",
        popular: true,
        wishlisted: false,
    },
    {
        id: 16,
        title: "Le Meridien",
        imgUrl: "https://www.holidify.com/images/cmsuploads/compressed/100722895_20210512140405.jpg",
        address: "Juhu Hotels, Mumbai",
        location: "Mumbai",
        price: 6700,
        beds: 3,
        bathrooms: 2,
        area: 1600,
        date: new Date(),
        proptype: "Hotel",
        popular: true,
        wishlisted: false,
    },
    {
        id: 17,
        title: "The Oberoi",
        imgUrl: "https://qtxasset.com/quartz/qcloud1/media/image/luxurytraveladvisor/1594135552/Cape%20Fahn%2001.jpg/Cape%20Fahn%2001.jpg?VersionId=ZTfcf2fMAwWX9xeQleAceYiwhWMiF7e9",
        address: "Hotels in MG Road, Bangalore",
        location: "Bangalore",
        price: 7400,
        beds: 3,
        bathrooms: 4,
        area: 1900,
        date: new Date(),
        proptype: "Hotel",
        popular: true,
        wishlisted: false,
    },
    {
        id: 18,
        title: "The Manohar",
        imgUrl: "https://img.traveltriangle.com/blog/wp-content/uploads/2017/12/cover4.jpg",
        address: "Gachibowli, Hyderabad",
        location: "Hyderabad",
        price: 5000,
        beds: 3,
        bathrooms: 3,
        area: 1400,
        date: new Date(),
        proptype: "Hotel",
        popular: false,
        wishlisted: false,
    },
    {
        id: 19,
        title: "Dreamz Lodge",
        imgUrl: "https://cdn.kiwicollection.com/media/property/PR003171/l/003171-01-Lion%20Sands_Ivory%20Lodge_3_Villa%20Private%20Deck%20and%20Plunge%20Pool7-Lion%20Sands%20Ivory%20Lodge.jpg?cb=1623715490",
        address: "Sudhama Nagar, Bangalore",
        location: "Bangalore",
        price: 4000,
        beds: 2,
        bathrooms: 2,
        area: 1100,
        date: new Date(),
        proptype: "Lodging",
        popular: true,
        wishlisted: false,
    },
    {
        id: 20,
        title: "Royal Regency Lodge",
        imgUrl: "https://moneyinc.com/wp-content/uploads/2016/06/South-Africa-Lodges.jpg",
        address: "Near Airport, Hyderabad",
        location: "Hyderabad",
        price: 6000,
        beds: 4,
        bathrooms: 4,
        area: 3000,
        date: new Date(),
        proptype: "Lodging",
        popular: true,
        wishlisted: false,
    }
]