export const propertylist = [
    {
        id: 1,
        title: "Casagrand Florella",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/phase-2-banner-thumb-1.jpg_ver=1.200?updatedAt=1691841176312",
        address: "Sarjapura, Bangalore",
        location: "Bangalore",
        price: 11000,
        beds: 3,
        bathrooms: 4,
        area: 3300,
        date: new Date(),
        proptype: "Villa",
        popular: true,
        wishlisted: false,
    },
    {
        id: 2,
        title: "Casagrand Florella Phase 2",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/thumb-1.jpg_ver=1.200?updatedAt=1691841245519",
        address: "Sarjapura, Bangalore",
        location: "Bangalore",
        price: 12500,
        beds: 4,
        bathrooms: 4,
        area: 4500,
        date: new Date(),
        proptype: "Villa",
        popular: false,
        wishlisted: false,
    },
    {
        id: 3,
        title: "VK Gardends Propbuysell",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/vk_gardens_propbuynsell-gandi_maisamma-hyderabad-vk_corporation.jpeg.webp?updatedAt=1691841281493",
        address: "Gandi Maisamma, North Hyderabad,",
        location: "Hyderabad",
        price: 4500,
        beds: 3,
        bathrooms: 3,
        area: 4000,
        date: new Date(),
        proptype: "Villa",
        popular: true,
        wishlisted: false,
    },
    {
        id: 4,
        title: "North Star",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/10-Villa-Projects-In-Hyderabad-1.jpg?updatedAt=1691841322670",
        address: "Tellapur, Hyderabad",
        location: "Hyderabad",
        price: 9500,
        beds: 4,
        bathrooms: 3,
        area: 4200,
        date: new Date(),
        proptype: "Villa",
        popular: false,
        wishlisted: false,
    },
    {
        id: 5,
        title: "RK Villas",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/istockphoto-1221865614-612x612.jpg?updatedAt=1691841366199",
        address: "Lonavala, Mumbai",
        location: "Mumbai",
        price: 8000,
        beds: 3,
        bathrooms: 4,
        area: 3800,
        date: new Date(),
        proptype: "Villa",
        popular: true,
        wishlisted: false,
    },
    {
        id: 6,
        title: "Asset Villas",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/ei26pavaw50cc05qxz1b4yi8q6kx_JPEG43.JPG?updatedAt=1691841412359",
        address: "Alibag, Mumbai",
        location: "Mumbai",
        price: 7000,
        beds: 2,
        bathrooms: 3,
        area: 3000,
        date: new Date(),
        proptype: "Villa",
        popular: false,
        wishlisted: false,
    },    {
        id: 7,
        title: "Deep Villa",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/Deep-Villa-Atrey-and-Associates-New-Delhi-ndia-Amazing-Architecture-House.jpg?updatedAt=1691841648443",
        address: " Pitampura, New Delhi",
        location: "Delhi",
        price: 10500,
        beds: 4,
        bathrooms: 4,
        area: 3000,
        date: new Date(),
        proptype: "Villa",
        popular: true,
        wishlisted: false,
    },
    {
        id: 8,
        title: "Kautilya Marg",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/imagereader.webp?updatedAt=1691841667231",
        address: "DL 110021, New Delhi",
        location: "Delhi",
        price: 12000,
        beds: 3,
        bathrooms: 3,
        area: 3000,
        date: new Date(),
        proptype: "Villa",
        popular: false,
        wishlisted: false,
    },
    {
        id: 9,
        title: "Casagrand Hazen",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/372-x-202.png_ver=1.200?updatedAt=1691842032191",
        address: "Bannerghatta Road, Bangalore",
        location: "Bangalore",
        price: 13000,
        beds: 3,
        bathrooms: 2,
        area: 1500,
        date: new Date(),
        proptype: "Apartment",
        popular: true,
        wishlisted: false,
    },
    {
        id: 10,
        title: "Casagrand Lorenza",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/1sideview.jpg_ver=1.200?updatedAt=1691842067553",
        address: "Hennur Main Road, Bangalore",
        location: "Bangalore",
        price: 12500,
        beds: 3,
        bathrooms: 3,
        area: 1800,
        date: new Date(),
        proptype: "Apartment",
        popular: true,
        wishlisted: false,
    },
    {
        id: 11,
        title: "Brigade Apartments",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/1432013636555acb44e3462.jpg?updatedAt=1691842124097",
        address: "Banjara Hills, Hyderabad",
        location: "Hyderabad",
        price: 11000,
        beds: 2,
        bathrooms: 2,
        area: 1500,
        date: new Date(),
        proptype: "Apartment",
        popular: false,
        wishlisted: false,
    },
    {
        id: 12,
        title: "Prestige High Fields",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/Aparna-Serene-Park-Apartments-Kondapur-Hyderabad.jpg?updatedAt=1691842252989",
        address: "Kondapur, Hyderabad",
        location: "Hyderabad",
        price: 12000,
        beds: 3,
        bathrooms: 2,
        area: 1300,
        date: new Date(),
        proptype: "Apartment",
        popular: true,
        wishlisted: false,
    },
    {
        id: 13,
        title: "Starlite Lotus Apartments",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/mumbai-apartment-pka-interior-design-feature-02-866x487-1366x768.jpg?updatedAt=1691842303357",
        address: "Apartment Goregaon East, Mumbai",
        location: "Mumbai",
        price: 12300,
        beds: 3,
        bathrooms: 3,
        area: 1000,
        date: new Date(),
        proptype: "Apartment",
        popular: true,
        wishlisted: false,
    },
    {
        id: 14,
        title: "Karmvir Empire",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/shree_developers_shree_siddhi_apartment_mumbai-seawoods-mumbai-shree_developers.jpg?updatedAt=1691842514879",
        address: "Apartment Chintal, Mumbai",
        location: "Mumbai",
        price: 9500,
        beds: 2,
        bathrooms: 3,
        area: 1020,
        date: new Date(),
        proptype: "Apartment",
        popular: false,
        wishlisted: false,
    },
    {
        id: 15,
        title: "Eros Hotel",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/58015405.cms?updatedAt=1691842557616",
        address: "Nehru Place, Delhi",
        location: "Delhi",
        price: 14000,
        beds: 3,
        bathrooms: 4,
        area: 1700,
        date: new Date(),
        proptype: "Hotel",
        popular: true,
        wishlisted: false,
    },
    {
        id: 16,
        title: "Le Meridien",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/100722895_20210512140405.jpg?updatedAt=1691842617572",
        address: "Juhu Hotels, Mumbai",
        location: "Mumbai",
        price: 6700,
        beds: 3,
        bathrooms: 2,
        area: 1600,
        date: new Date(),
        proptype: "Hotel",
        popular: true,
        wishlisted: false,
    },
    {
        id: 17,
        title: "The Oberoi",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/Cape_20Fahn_2001.jpg_VersionId=ZTfcf2fMAwWX9xeQleAceYiwhWMiF7e9?updatedAt=1691842679430",
        address: "Hotels in MG Road, Bangalore",
        location: "Bangalore",
        price: 7400,
        beds: 3,
        bathrooms: 4,
        area: 1900,
        date: new Date(),
        proptype: "Hotel",
        popular: true,
        wishlisted: false,
    },
    {
        id: 18,
        title: "The Manohar",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/cover4.jpg?updatedAt=1691842733671",
        address: "Gachibowli, Hyderabad",
        location: "Hyderabad",
        price: 5000,
        beds: 3,
        bathrooms: 3,
        area: 1400,
        date: new Date(),
        proptype: "Hotel",
        popular: false,
        wishlisted: false,
    },
    {
        id: 19,
        title: "Dreamz Lodge",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/003171-01-Lion_20Sands_Ivory_20Lodge_3_Villa_20Private_20Deck_20and_20Plunge_20Pool7-Lion_20Sands_20Ivory_20Lodge.jpg_cb=1623715490?updatedAt=1691842790853",
        address: "Sudhama Nagar, Bangalore",
        location: "Bangalore",
        price: 4000,
        beds: 2,
        bathrooms: 2,
        area: 1100,
        date: new Date(),
        proptype: "Lodging",
        popular: true,
        wishlisted: false,
    },
    {
        id: 20,
        title: "Royal Regency Lodge",
        imgUrl: "https://ik.imagekit.io/wqjwh0cz6/Estatery/South-Africa-Lodges.jpg?updatedAt=1691842826575",
        address: "Near Airport, Hyderabad",
        location: "Hyderabad",
        price: 6000,
        beds: 4,
        bathrooms: 4,
        area: 3000,
        date: new Date(),
        proptype: "Lodging",
        popular: true,
        wishlisted: false,
    }
]